usr/bin/mysql_config
usr/include/mysql/*.h
usr/include/mysql/mysql/*.h
usr/include/mysql/mysql/*.h.pp
usr/include/mysql/mysql/plugin_auth_common.h usr/include/mysql
usr/include/mysql/mysql/psi/*.h
usr/include/mysql/mysql/psi/psi_base.h usr/include/mysql/psi
usr/include/mysql/mysql/psi/psi_memory.h usr/include/mysql/psi
usr/lib/*/libmysqlclient.a
usr/lib/*/libmysqlclient.so
usr/lib/*/pkgconfig/mysqlclient.pc
usr/share/aclocal/mysql.m4
